keys:
  - &kamov age1333pggxjytjnsw8zwd2d03suywxfexeydwlk8hfgs4j49lskcutqc7aze7
  - &megumu age1d96wz0qq6q2yz7zajlle6zeqta2lylkvcjearq6v9eg0pln6hvgsl3z7p9

creation_rules:
  - path_regex: ^sops/kamov.yaml$
    key_groups:
      - age: [*kamov]

  - path_regex: ^.*/megumu/.*\.ya?ml$
    key_groups:
      - age: [*megumu]
